/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as EmergencySupportRouteImport } from './routes/emergency-support'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CancellationRefundPolicyRouteImport } from './routes/cancellation-refund-policy'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageReferenceRouteImport } from './routes/manage.$reference'
import { Route as BookPaymentCallbackRouteImport } from './routes/book.payment-callback'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedTherapistRouteImport } from './routes/_authenticated.therapist'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ContentKindSlugRouteImport } from './routes/content.$kind.$slug'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as AuthenticatedAdminTherapistsRouteImport } from './routes/_authenticated.admin.therapists'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated.admin.testimonials'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated.admin.services'
import { Route as AuthenticatedAdminRedirectsRouteImport } from './routes/_authenticated.admin.redirects'
import { Route as AuthenticatedAdminPublicPagesRouteImport } from './routes/_authenticated.admin.public-pages'
import { Route as AuthenticatedAdminProgressRouteImport } from './routes/_authenticated.admin.progress'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated.admin.pages'
import { Route as AuthenticatedAdminMigrationRouteImport } from './routes/_authenticated.admin.migration'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated.admin.messages'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated.admin.media'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated.admin.journal'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated.admin.homepage'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated.admin.hero'
import { Route as AuthenticatedAdminGoogleReviewsRouteImport } from './routes/_authenticated.admin.google-reviews'
import { Route as AuthenticatedAdminGoogleRouteImport } from './routes/_authenticated.admin.google'
import { Route as AuthenticatedAdminFormsRouteImport } from './routes/_authenticated.admin.forms'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated.admin.faqs'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated.admin.emails'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated.admin.clients'
import { Route as AuthenticatedAdminCarouselRouteImport } from './routes/_authenticated.admin.carousel'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated.admin.bookings'
import { Route as AuthenticatedAdminAvailabilityRouteImport } from './routes/_authenticated.admin.availability'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'
import { Route as AuthenticatedAccountAppointmentsRouteImport } from './routes/_authenticated.account_.appointments'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated.admin.clients.index'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicHooksRetryEmailsRouteImport } from './routes/api/public/hooks/retry-emails'
import { Route as ApiPublicHooksRefreshGoogleReviewsRouteImport } from './routes/api/public/hooks/refresh-google-reviews'
import { Route as ApiPublicHooksRecheckPaymentsRouteImport } from './routes/api/public/hooks/recheck-payments'
import { Route as ApiPublicHooksPublishScheduledRouteImport } from './routes/api/public/hooks/publish-scheduled'
import { Route as ApiPublicGooglePushRouteImport } from './routes/api/public/google/push'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'
import { Route as AuthenticatedAdminClientsClientIdRouteImport } from './routes/_authenticated.admin.clients.$clientId'
import { Route as AuthenticatedAdminBookingsNewRouteImport } from './routes/_authenticated.admin.bookings.new'
import { Route as AuthenticatedAdminPreviewKindSlugRouteImport } from './routes/_authenticated.admin.preview.$kind.$slug'
import { Route as AuthenticatedAdminContentIdEditRouteImport } from './routes/_authenticated.admin.content.$id.edit'

const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencySupportRoute = EmergencySupportRouteImport.update({
  id: '/emergency-support',
  path: '/emergency-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRefundPolicyRoute =
  CancellationRefundPolicyRouteImport.update({
    id: '/cancellation-refund-policy',
    path: '/cancellation-refund-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageReferenceRoute = ManageReferenceRouteImport.update({
  id: '/manage/$reference',
  path: '/manage/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPaymentCallbackRoute = BookPaymentCallbackRouteImport.update({
  id: '/payment-callback',
  path: '/payment-callback',
  getParentRoute: () => BookRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedTherapistRoute = AuthenticatedTherapistRouteImport.update({
  id: '/therapist',
  path: '/therapist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ContentKindSlugRoute = ContentKindSlugRouteImport.update({
  id: '/content/$kind/$slug',
  path: '/content/$kind/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminTherapistsRoute =
  AuthenticatedAdminTherapistsRouteImport.update({
    id: '/therapists',
    path: '/therapists',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRedirectsRoute =
  AuthenticatedAdminRedirectsRouteImport.update({
    id: '/redirects',
    path: '/redirects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPublicPagesRoute =
  AuthenticatedAdminPublicPagesRouteImport.update({
    id: '/public-pages',
    path: '/public-pages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProgressRoute =
  AuthenticatedAdminProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMigrationRoute =
  AuthenticatedAdminMigrationRouteImport.update({
    id: '/migration',
    path: '/migration',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGoogleReviewsRoute =
  AuthenticatedAdminGoogleReviewsRouteImport.update({
    id: '/google-reviews',
    path: '/google-reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGoogleRoute =
  AuthenticatedAdminGoogleRouteImport.update({
    id: '/google',
    path: '/google',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFormsRoute = AuthenticatedAdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCarouselRoute =
  AuthenticatedAdminCarouselRouteImport.update({
    id: '/carousel',
    path: '/carousel',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAvailabilityRoute =
  AuthenticatedAdminAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountAppointmentsRoute =
  AuthenticatedAccountAppointmentsRouteImport.update({
    id: '/account_/appointments',
    path: '/account/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRetryEmailsRoute =
  ApiPublicHooksRetryEmailsRouteImport.update({
    id: '/api/public/hooks/retry-emails',
    path: '/api/public/hooks/retry-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshGoogleReviewsRoute =
  ApiPublicHooksRefreshGoogleReviewsRouteImport.update({
    id: '/api/public/hooks/refresh-google-reviews',
    path: '/api/public/hooks/refresh-google-reviews',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecheckPaymentsRoute =
  ApiPublicHooksRecheckPaymentsRouteImport.update({
    id: '/api/public/hooks/recheck-payments',
    path: '/api/public/hooks/recheck-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPublishScheduledRoute =
  ApiPublicHooksPublishScheduledRouteImport.update({
    id: '/api/public/hooks/publish-scheduled',
    path: '/api/public/hooks/publish-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGooglePushRoute = ApiPublicGooglePushRouteImport.update({
  id: '/api/public/google/push',
  path: '/api/public/google/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminClientsClientIdRoute =
  AuthenticatedAdminClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminBookingsNewRoute =
  AuthenticatedAdminBookingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminBookingsRoute,
  } as any)
const AuthenticatedAdminPreviewKindSlugRoute =
  AuthenticatedAdminPreviewKindSlugRouteImport.update({
    id: '/preview/$kind/$slug',
    path: '/preview/$kind/$slug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentIdEditRoute =
  AuthenticatedAdminContentIdEditRouteImport.update({
    id: '/content/$id/edit',
    path: '/content/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/cancellation-refund-policy': typeof CancellationRefundPolicyRoute
  '/contact': typeof ContactRoute
  '/emergency-support': typeof EmergencySupportRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase': typeof PurchaseRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/therapist': typeof AuthenticatedTherapistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/payment-callback': typeof BookPaymentCallbackRoute
  '/manage/$reference': typeof ManageReferenceRoute
  '/account/appointments': typeof AuthenticatedAccountAppointmentsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRouteWithChildren
  '/admin/carousel': typeof AuthenticatedAdminCarouselRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/admin/google': typeof AuthenticatedAdminGoogleRoute
  '/admin/google-reviews': typeof AuthenticatedAdminGoogleReviewsRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/progress': typeof AuthenticatedAdminProgressRoute
  '/admin/public-pages': typeof AuthenticatedAdminPublicPagesRoute
  '/admin/redirects': typeof AuthenticatedAdminRedirectsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/therapists': typeof AuthenticatedAdminTherapistsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/content/$kind/$slug': typeof ContentKindSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/google/push': typeof ApiPublicGooglePushRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
  '/api/public/hooks/recheck-payments': typeof ApiPublicHooksRecheckPaymentsRoute
  '/api/public/hooks/refresh-google-reviews': typeof ApiPublicHooksRefreshGoogleReviewsRoute
  '/api/public/hooks/retry-emails': typeof ApiPublicHooksRetryEmailsRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/content/$id/edit': typeof AuthenticatedAdminContentIdEditRoute
  '/admin/preview/$kind/$slug': typeof AuthenticatedAdminPreviewKindSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/cancellation-refund-policy': typeof CancellationRefundPolicyRoute
  '/contact': typeof ContactRoute
  '/emergency-support': typeof EmergencySupportRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase': typeof PurchaseRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/therapist': typeof AuthenticatedTherapistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/payment-callback': typeof BookPaymentCallbackRoute
  '/manage/$reference': typeof ManageReferenceRoute
  '/account/appointments': typeof AuthenticatedAccountAppointmentsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRouteWithChildren
  '/admin/carousel': typeof AuthenticatedAdminCarouselRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/admin/google': typeof AuthenticatedAdminGoogleRoute
  '/admin/google-reviews': typeof AuthenticatedAdminGoogleReviewsRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/progress': typeof AuthenticatedAdminProgressRoute
  '/admin/public-pages': typeof AuthenticatedAdminPublicPagesRoute
  '/admin/redirects': typeof AuthenticatedAdminRedirectsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/therapists': typeof AuthenticatedAdminTherapistsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/content/$kind/$slug': typeof ContentKindSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/google/push': typeof ApiPublicGooglePushRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
  '/api/public/hooks/recheck-payments': typeof ApiPublicHooksRecheckPaymentsRoute
  '/api/public/hooks/refresh-google-reviews': typeof ApiPublicHooksRefreshGoogleReviewsRoute
  '/api/public/hooks/retry-emails': typeof ApiPublicHooksRetryEmailsRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/content/$id/edit': typeof AuthenticatedAdminContentIdEditRoute
  '/admin/preview/$kind/$slug': typeof AuthenticatedAdminPreviewKindSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/cancellation-refund-policy': typeof CancellationRefundPolicyRoute
  '/contact': typeof ContactRoute
  '/emergency-support': typeof EmergencySupportRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase': typeof PurchaseRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/therapist': typeof AuthenticatedTherapistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/payment-callback': typeof BookPaymentCallbackRoute
  '/manage/$reference': typeof ManageReferenceRoute
  '/_authenticated/account_/appointments': typeof AuthenticatedAccountAppointmentsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRouteWithChildren
  '/_authenticated/admin/carousel': typeof AuthenticatedAdminCarouselRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/_authenticated/admin/google': typeof AuthenticatedAdminGoogleRoute
  '/_authenticated/admin/google-reviews': typeof AuthenticatedAdminGoogleReviewsRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/progress': typeof AuthenticatedAdminProgressRoute
  '/_authenticated/admin/public-pages': typeof AuthenticatedAdminPublicPagesRoute
  '/_authenticated/admin/redirects': typeof AuthenticatedAdminRedirectsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/therapists': typeof AuthenticatedAdminTherapistsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/content/$kind/$slug': typeof ContentKindSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/_authenticated/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/google/push': typeof ApiPublicGooglePushRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
  '/api/public/hooks/recheck-payments': typeof ApiPublicHooksRecheckPaymentsRoute
  '/api/public/hooks/refresh-google-reviews': typeof ApiPublicHooksRefreshGoogleReviewsRoute
  '/api/public/hooks/retry-emails': typeof ApiPublicHooksRetryEmailsRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/content/$id/edit': typeof AuthenticatedAdminContentIdEditRoute
  '/_authenticated/admin/preview/$kind/$slug': typeof AuthenticatedAdminPreviewKindSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/cancellation-refund-policy'
    | '/contact'
    | '/emergency-support'
    | '/faqs'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/purchase'
    | '/reset-password'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/therapists'
    | '/account'
    | '/admin'
    | '/therapist'
    | '/blog/$slug'
    | '/book/payment-callback'
    | '/manage/$reference'
    | '/account/appointments'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/carousel'
    | '/admin/clients'
    | '/admin/emails'
    | '/admin/faqs'
    | '/admin/forms'
    | '/admin/google'
    | '/admin/google-reviews'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/journal'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/migration'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/progress'
    | '/admin/public-pages'
    | '/admin/redirects'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/therapists'
    | '/api/public/paystack-webhook'
    | '/content/$kind/$slug'
    | '/admin/'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/api/public/google/callback'
    | '/api/public/google/push'
    | '/api/public/hooks/publish-scheduled'
    | '/api/public/hooks/recheck-payments'
    | '/api/public/hooks/refresh-google-reviews'
    | '/api/public/hooks/retry-emails'
    | '/api/public/hooks/send-reminders'
    | '/admin/clients/'
    | '/admin/content/$id/edit'
    | '/admin/preview/$kind/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/cancellation-refund-policy'
    | '/contact'
    | '/emergency-support'
    | '/faqs'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/purchase'
    | '/reset-password'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/therapists'
    | '/account'
    | '/therapist'
    | '/blog/$slug'
    | '/book/payment-callback'
    | '/manage/$reference'
    | '/account/appointments'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/carousel'
    | '/admin/emails'
    | '/admin/faqs'
    | '/admin/forms'
    | '/admin/google'
    | '/admin/google-reviews'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/journal'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/migration'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/progress'
    | '/admin/public-pages'
    | '/admin/redirects'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/therapists'
    | '/api/public/paystack-webhook'
    | '/content/$kind/$slug'
    | '/admin'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/api/public/google/callback'
    | '/api/public/google/push'
    | '/api/public/hooks/publish-scheduled'
    | '/api/public/hooks/recheck-payments'
    | '/api/public/hooks/refresh-google-reviews'
    | '/api/public/hooks/retry-emails'
    | '/api/public/hooks/send-reminders'
    | '/admin/clients'
    | '/admin/content/$id/edit'
    | '/admin/preview/$kind/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/book'
    | '/cancellation-refund-policy'
    | '/contact'
    | '/emergency-support'
    | '/faqs'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/purchase'
    | '/reset-password'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/therapists'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/therapist'
    | '/blog/$slug'
    | '/book/payment-callback'
    | '/manage/$reference'
    | '/_authenticated/account_/appointments'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/availability'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/carousel'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/forms'
    | '/_authenticated/admin/google'
    | '/_authenticated/admin/google-reviews'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/migration'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/progress'
    | '/_authenticated/admin/public-pages'
    | '/_authenticated/admin/redirects'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/therapists'
    | '/api/public/paystack-webhook'
    | '/content/$kind/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/bookings/new'
    | '/_authenticated/admin/clients/$clientId'
    | '/api/public/google/callback'
    | '/api/public/google/push'
    | '/api/public/hooks/publish-scheduled'
    | '/api/public/hooks/recheck-payments'
    | '/api/public/hooks/refresh-google-reviews'
    | '/api/public/hooks/retry-emails'
    | '/api/public/hooks/send-reminders'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/content/$id/edit'
    | '/_authenticated/admin/preview/$kind/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookRoute: typeof BookRouteWithChildren
  CancellationRefundPolicyRoute: typeof CancellationRefundPolicyRoute
  ContactRoute: typeof ContactRoute
  EmergencySupportRoute: typeof EmergencySupportRoute
  FaqsRoute: typeof FaqsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PurchaseRoute: typeof PurchaseRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TherapistsRoute: typeof TherapistsRoute
  ManageReferenceRoute: typeof ManageReferenceRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ContentKindSlugRoute: typeof ContentKindSlugRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicGooglePushRoute: typeof ApiPublicGooglePushRoute
  ApiPublicHooksPublishScheduledRoute: typeof ApiPublicHooksPublishScheduledRoute
  ApiPublicHooksRecheckPaymentsRoute: typeof ApiPublicHooksRecheckPaymentsRoute
  ApiPublicHooksRefreshGoogleReviewsRoute: typeof ApiPublicHooksRefreshGoogleReviewsRoute
  ApiPublicHooksRetryEmailsRoute: typeof ApiPublicHooksRetryEmailsRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-support': {
      id: '/emergency-support'
      path: '/emergency-support'
      fullPath: '/emergency-support'
      preLoaderRoute: typeof EmergencySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-refund-policy': {
      id: '/cancellation-refund-policy'
      path: '/cancellation-refund-policy'
      fullPath: '/cancellation-refund-policy'
      preLoaderRoute: typeof CancellationRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$reference': {
      id: '/manage/$reference'
      path: '/manage/$reference'
      fullPath: '/manage/$reference'
      preLoaderRoute: typeof ManageReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/payment-callback': {
      id: '/book/payment-callback'
      path: '/payment-callback'
      fullPath: '/book/payment-callback'
      preLoaderRoute: typeof BookPaymentCallbackRouteImport
      parentRoute: typeof BookRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/therapist': {
      id: '/_authenticated/therapist'
      path: '/therapist'
      fullPath: '/therapist'
      preLoaderRoute: typeof AuthenticatedTherapistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/content/$kind/$slug': {
      id: '/content/$kind/$slug'
      path: '/content/$kind/$slug'
      fullPath: '/content/$kind/$slug'
      preLoaderRoute: typeof ContentKindSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/therapists': {
      id: '/_authenticated/admin/therapists'
      path: '/therapists'
      fullPath: '/admin/therapists'
      preLoaderRoute: typeof AuthenticatedAdminTherapistsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/redirects': {
      id: '/_authenticated/admin/redirects'
      path: '/redirects'
      fullPath: '/admin/redirects'
      preLoaderRoute: typeof AuthenticatedAdminRedirectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/public-pages': {
      id: '/_authenticated/admin/public-pages'
      path: '/public-pages'
      fullPath: '/admin/public-pages'
      preLoaderRoute: typeof AuthenticatedAdminPublicPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/progress': {
      id: '/_authenticated/admin/progress'
      path: '/progress'
      fullPath: '/admin/progress'
      preLoaderRoute: typeof AuthenticatedAdminProgressRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/migration': {
      id: '/_authenticated/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AuthenticatedAdminMigrationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/google-reviews': {
      id: '/_authenticated/admin/google-reviews'
      path: '/google-reviews'
      fullPath: '/admin/google-reviews'
      preLoaderRoute: typeof AuthenticatedAdminGoogleReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/google': {
      id: '/_authenticated/admin/google'
      path: '/google'
      fullPath: '/admin/google'
      preLoaderRoute: typeof AuthenticatedAdminGoogleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/forms': {
      id: '/_authenticated/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AuthenticatedAdminFormsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/carousel': {
      id: '/_authenticated/admin/carousel'
      path: '/carousel'
      fullPath: '/admin/carousel'
      preLoaderRoute: typeof AuthenticatedAdminCarouselRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/availability': {
      id: '/_authenticated/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AuthenticatedAdminAvailabilityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account_/appointments': {
      id: '/_authenticated/account_/appointments'
      path: '/account/appointments'
      fullPath: '/account/appointments'
      preLoaderRoute: typeof AuthenticatedAccountAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retry-emails': {
      id: '/api/public/hooks/retry-emails'
      path: '/api/public/hooks/retry-emails'
      fullPath: '/api/public/hooks/retry-emails'
      preLoaderRoute: typeof ApiPublicHooksRetryEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-google-reviews': {
      id: '/api/public/hooks/refresh-google-reviews'
      path: '/api/public/hooks/refresh-google-reviews'
      fullPath: '/api/public/hooks/refresh-google-reviews'
      preLoaderRoute: typeof ApiPublicHooksRefreshGoogleReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recheck-payments': {
      id: '/api/public/hooks/recheck-payments'
      path: '/api/public/hooks/recheck-payments'
      fullPath: '/api/public/hooks/recheck-payments'
      preLoaderRoute: typeof ApiPublicHooksRecheckPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-scheduled': {
      id: '/api/public/hooks/publish-scheduled'
      path: '/api/public/hooks/publish-scheduled'
      fullPath: '/api/public/hooks/publish-scheduled'
      preLoaderRoute: typeof ApiPublicHooksPublishScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/push': {
      id: '/api/public/google/push'
      path: '/api/public/google/push'
      fullPath: '/api/public/google/push'
      preLoaderRoute: typeof ApiPublicGooglePushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/clients/$clientId': {
      id: '/_authenticated/admin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedAdminClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/bookings/new': {
      id: '/_authenticated/admin/bookings/new'
      path: '/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AuthenticatedAdminBookingsNewRouteImport
      parentRoute: typeof AuthenticatedAdminBookingsRoute
    }
    '/_authenticated/admin/preview/$kind/$slug': {
      id: '/_authenticated/admin/preview/$kind/$slug'
      path: '/preview/$kind/$slug'
      fullPath: '/admin/preview/$kind/$slug'
      preLoaderRoute: typeof AuthenticatedAdminPreviewKindSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content/$id/edit': {
      id: '/_authenticated/admin/content/$id/edit'
      path: '/content/$id/edit'
      fullPath: '/admin/content/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminContentIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminBookingsRouteChildren {
  AuthenticatedAdminBookingsNewRoute: typeof AuthenticatedAdminBookingsNewRoute
}

const AuthenticatedAdminBookingsRouteChildren: AuthenticatedAdminBookingsRouteChildren =
  {
    AuthenticatedAdminBookingsNewRoute: AuthenticatedAdminBookingsNewRoute,
  }

const AuthenticatedAdminBookingsRouteWithChildren =
  AuthenticatedAdminBookingsRoute._addFileChildren(
    AuthenticatedAdminBookingsRouteChildren,
  )

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsClientIdRoute: typeof AuthenticatedAdminClientsClientIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsClientIdRoute:
      AuthenticatedAdminClientsClientIdRoute,
    AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminAvailabilityRoute: typeof AuthenticatedAdminAvailabilityRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRouteWithChildren
  AuthenticatedAdminCarouselRoute: typeof AuthenticatedAdminCarouselRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminFormsRoute: typeof AuthenticatedAdminFormsRoute
  AuthenticatedAdminGoogleRoute: typeof AuthenticatedAdminGoogleRoute
  AuthenticatedAdminGoogleReviewsRoute: typeof AuthenticatedAdminGoogleReviewsRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminMigrationRoute: typeof AuthenticatedAdminMigrationRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProgressRoute: typeof AuthenticatedAdminProgressRoute
  AuthenticatedAdminPublicPagesRoute: typeof AuthenticatedAdminPublicPagesRoute
  AuthenticatedAdminRedirectsRoute: typeof AuthenticatedAdminRedirectsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTherapistsRoute: typeof AuthenticatedAdminTherapistsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminContentIdEditRoute: typeof AuthenticatedAdminContentIdEditRoute
  AuthenticatedAdminPreviewKindSlugRoute: typeof AuthenticatedAdminPreviewKindSlugRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminAvailabilityRoute: AuthenticatedAdminAvailabilityRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRouteWithChildren,
  AuthenticatedAdminCarouselRoute: AuthenticatedAdminCarouselRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminFormsRoute: AuthenticatedAdminFormsRoute,
  AuthenticatedAdminGoogleRoute: AuthenticatedAdminGoogleRoute,
  AuthenticatedAdminGoogleReviewsRoute: AuthenticatedAdminGoogleReviewsRoute,
  AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminMigrationRoute: AuthenticatedAdminMigrationRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProgressRoute: AuthenticatedAdminProgressRoute,
  AuthenticatedAdminPublicPagesRoute: AuthenticatedAdminPublicPagesRoute,
  AuthenticatedAdminRedirectsRoute: AuthenticatedAdminRedirectsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminTherapistsRoute: AuthenticatedAdminTherapistsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminContentIdEditRoute: AuthenticatedAdminContentIdEditRoute,
  AuthenticatedAdminPreviewKindSlugRoute:
    AuthenticatedAdminPreviewKindSlugRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedTherapistRoute: typeof AuthenticatedTherapistRoute
  AuthenticatedAccountAppointmentsRoute: typeof AuthenticatedAccountAppointmentsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedTherapistRoute: AuthenticatedTherapistRoute,
  AuthenticatedAccountAppointmentsRoute: AuthenticatedAccountAppointmentsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface BookRouteChildren {
  BookPaymentCallbackRoute: typeof BookPaymentCallbackRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookPaymentCallbackRoute: BookPaymentCallbackRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BookRoute: BookRouteWithChildren,
  CancellationRefundPolicyRoute: CancellationRefundPolicyRoute,
  ContactRoute: ContactRoute,
  EmergencySupportRoute: EmergencySupportRoute,
  FaqsRoute: FaqsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PurchaseRoute: PurchaseRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TherapistsRoute: TherapistsRoute,
  ManageReferenceRoute: ManageReferenceRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ContentKindSlugRoute: ContentKindSlugRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicGooglePushRoute: ApiPublicGooglePushRoute,
  ApiPublicHooksPublishScheduledRoute: ApiPublicHooksPublishScheduledRoute,
  ApiPublicHooksRecheckPaymentsRoute: ApiPublicHooksRecheckPaymentsRoute,
  ApiPublicHooksRefreshGoogleReviewsRoute:
    ApiPublicHooksRefreshGoogleReviewsRoute,
  ApiPublicHooksRetryEmailsRoute: ApiPublicHooksRetryEmailsRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
